
spring:
  security:
    jwt:
      secret: a21d1c916ba20fed582b5cb4d11582674bc5c65bef2493bd700de202401bbdfd
      expiration: 3600000
  application:
    name: user-service
  datasource:
    username: ${database.username}
    password: ${database.password}
    url: ${database.url}
  liquibase:
    change-log: classpath:db.changelog/db.changelog-master.xml
    enabled: true
    default-schema: ${database.schema}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_catalog: ${database.name}
        default_schema: ${database.schema}
        order_by:
          default_null_ordering: last

database:
  url: jdbc:postgresql://localhost:55550/ems
  username: postgres
  password: postgres
  schema: usersettings
server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
