spring:
  application:
    name: employee-service
  datasource:
    username: ${database.username}
    password: ${database.password}
    url: ${database.url}

database:
  url: jdbc:postgresql://localhost:5555/ems
  username: postgres
  password: postgres